### ISSUE TITLE
JWT with CORS?

### ISSUE THREAD

**Issue by rmpugh** [zendesk/demo_apps#81]
Hi there,

If I add "cors: true" to the sampleRequest in the demo, the {{jwt.token}} is not replaced with the actual token when hitting the server. Is there additional changes I have to make or is this expected behavior?

Many thanks,
Rob

**Comment by sandlerr** [comment]
Hi Rob,
This is expected behaviour. Adding `cors: true` means you aren't able to use secure settings for that request. CORS requests are made directly from the browser to the cross-origin destination without using our secure proxy. The secure proxy is required to interpolate the value of a secure setting. If you want to interpolate values into CORS requests, they need to be normal (non-secure) settings.

**Comment by rmpugh** [comment]
Hey sandlerr,

Many thanks for the quick response - and thanks for clearing that up - makes complete sense.

**Comment by sandlerr** [comment]
Not a problem. If you haven't already, you may also find help from checking out our [community](https://support.zendesk.com/hc/en-us/community/topics/200132096-Zendesk-apps), [developer portal](https://developer.zendesk.com/apps/docs/agent/requests#secure-requests) or [opening a ticket](https://support.zendesk.com/hc/en-us/requests/new?ticket_form_id=253538).

Best of luck developing your app!
