### ISSUE TITLE
Hiding top-bar application on clicking outside of application

### ISSUE THREAD

**Issue by Utkarsh-Verma** [zendesk/demo_apps#89]
I have created zendesk app using app framework v1. The major issue I'm facing is that I want to close the app when the user clicks outside it. Zendesk Talk does it nicely but I'm unable to figure out a solution since I can't make app listen to the events outside its scope. 

I did read this thread - https://support.zendesk.com/hc/en-us/community/posts/202664363-Conditionally-hiding-an-app?input_string=Hiding%20Topbar%20A

But this.popover('hide') would require an event to close.
Any Ideas on how to achieve it?

**Comment by sandlerr** [comment]
Hi @Utkarsh-Verma you might like to try focussing your app's element when it is shown and listening for `blur` events.

**Comment by Utkarsh-Verma** [comment]
@sandlerr I have already tried this solution, but problem is that on app.activated event, this.$('.some_element') doesn't return element, so i am not able to add focus to element.

**Comment by sandlerr** [comment]
Perhaps your template is not yet rendered when the selector runs?

Since this issue doesn't relate to the demo apps in this repo I'm going to close it, but you are more than welcome to [contact us](https://support.zendesk.com/hc/en-us/requests/new?ticket_form_id=253538) for support on this specific problem.
